"""Add description column to book table

Revision ID: 7eeb3318566d
Revises: 9b2285db4548
Create Date: 2025-05-18 18:55:46.034920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7eeb3318566d"
down_revision: Union[str, None] = "9b2285db4548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "description")
    # ### end Alembic commands ###
